### ISSUE TITLE
`face.glyph.outline.decompose()` fails for some fonts?

### ISSUE THREAD

**Issue by loveencounterflow** [rougier/freetype-py#114]
I installed freetype-py from master (e8335bb) and tried out the [decompose example](https://github.com/rougier/freetype-py/blob/master/examples/glyph-vector-decompose.py#L29). This works and is pleasingly fast (no benchmarks yet, though). I realize decomposition renders an empty string when I load [Sun-ExtA](https://www.onlinewebfonts.com/download/55b8595740fcacc7c69e685c964f2868) and `face.load_char('國')`, though it does work with `face.load_char('A')`.

I tried to set another `charmap` with `face.set_charmap(1)` (the font has three charmaps), but to no avail. Is this maybe due to the font having an unusual outline format? It usually performs OK though, Sun-Exta.ttf is a pretty down-to earth, barebones and standard font that rarely causes problems IMHO.

**Comment by HinTak** [comment]
Sun-ExtA has an unusual charmap, but AFAIK the code should work. Can you try loading by glyph id instead of char code? loading by glyph id bypasses the charmap look-up, so would be more straight-forward.

**Comment by loveencounterflow** [comment]
Thanks for the fast answer. So I tried `face.load_glyph( face.get_char_index( 'A' ) )` and `face.load_char( face.get_char_index( '國' ) )`; this works for the first, but not the second, so the result is unchanged compared to using `load_char()`.

**Comment by duelafn** [comment]
Just trying out some things

* If I try using Vera.ttf, I get a rendering of the missing glyph box
* If I use NotoSerifCJK-Regular.ttc, I do get a decomposition

So, I'd definitely suspect something about the font – at this point I'd be surprised if a C program calling FT_Outline_Decompose() would produce anything.

**Comment by duelafn** [comment]
Yep, ran it through "example5" from https://www.freetype.org/freetype2/docs/tutorial/step3.html (after removing the single-byte restriction in the C++ source), and it says no outline present for the glyph. I don't think there's anything we can do about that.

**Comment by duelafn** [comment]
Opened the font in fontforge and it sure looks ok to my untrained eyes, so this may be an issue for freetype itself. Especially since support seems to be quite spotty.

Works: \u3004 \u3018 \u3333 \u4dc0-\u4dff \u9fa6

Fails: \u570b \u3000-\u3003 \u3004-\u3017 \u3400-\u4dbf \u4e00-\u9fa5

**Comment by loveencounterflow** [comment]
I'm running Linux Mint 19.1; isn't font rendering on this system done with freetype? I've been working many years with this exact font (and its earlier versions) and I've never had any issues with it, not on Windows, not on OSX, and not on Linux either.

In order to add a few data points on this problem, I disassembled the font with `ttx`, and that did issue some warnings:

```
➜  freetype-py-demo  ttx -o /tmp/sun-extav6.ttx ~/jzr/benchmarks/assets/ucdb/fonts/Sun-ExtAv6.ttf
Dumping "/home/flow/jzr/benchmarks/assets/ucdb/fonts/Sun-ExtAv6.ttf" to "/tmp/sun-extav6.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'fpgm' table...
Dumping 'prep' table...
Dumping 'cvt ' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'EBDT' table...
Dumping 'EBLC' table...
WARNING: ClassDef table has end glyph ID out of range: glyph50863.
WARNING: ClassDef table has start glyph ID out of range: glyph50864.
WARNING: ClassDef table has start glyph ID out of range: glyph50866.
WARNING: ClassDef table has start glyph ID out of range: glyph50878.
WARNING: ClassDef table has start glyph ID out of range: glyph50880.
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'VORG' table...
Dumping 'vhea' table...
WARNING: The vhea.numberOfVMetrics exceeds the maxp.numGlyphs
WARNING: too much 'vmtx' table data
Dumping 'vmtx' table...
```
Then I searched the file using `grep -n -C 1 -Pi '570b' -r /tmp/sun-extav6.ttx`. Leaving out some (I think irrelevant) lines that gives me:

```
18232-    <GlyphID id="18226" name="uni570A"/>
18233:    <GlyphID id="18227" name="uni570B"/>
18234-    <GlyphID id="18228" name="uni570C"/>
--
68447-    <mtx name="uni570A" width="256" lsb="31"/>
68448:    <mtx name="uni570B" width="256" lsb="28"/>
68449-    <mtx name="uni570C" width="256" lsb="29"/>
--
118608-      <map code="0x570a" name="uni570A"/><!-- CJK UNIFIED IDEOGRAPH-570A -->
118609:      <map code="0x570b" name="uni570B"/><!-- CJK UNIFIED IDEOGRAPH-570B -->
118610-      <map code="0x570c" name="uni570C"/><!-- CJK UNIFIED IDEOGRAPH-570C -->
--
169019-      <map code="0x570a" name="uni570A"/><!-- CJK UNIFIED IDEOGRAPH-570A -->
169020:      <map code="0x570b" name="uni570B"/><!-- CJK UNIFIED IDEOGRAPH-570B -->
169021-      <map code="0x570c" name="uni570C"/><!-- CJK UNIFIED IDEOGRAPH-570C -->
--
1872835-
1872836:    <TTGlyph name="uni570B" xMin="28" yMin="-26" xMax="235" yMax="209">
1872837-      <contour>
--
7219862-      </ebdt_bitmap_format_5>
7219863:      <ebdt_bitmap_format_5 name="uni570B">
7219864-        <rawimagedata>
--
7390397:      <ebdt_bitmap_format_5 name="uni570B">
7390398-        <rawimagedata>
--
8223676-        <glyphLoc id="18226" name="uni570A"/>
8223677:        <glyphLoc id="18227" name="uni570B"/>
8223678-        <glyphLoc id="18228" name="uni570C"/>
--
8252586-        <glyphLoc id="18226" name="uni570A"/>
8252587:        <glyphLoc id="18227" name="uni570B"/>
8252588-        <glyphLoc id="18228" name="uni570C"/>
--
8281496-        <glyphLoc id="18226" name="uni570A"/>
8281497:        <glyphLoc id="18227" name="uni570B"/>
8281498-        <glyphLoc id="18228" name="uni570C"/>
--
8310406-        <glyphLoc id="18226" name="uni570A"/>
8310407:        <glyphLoc id="18227" name="uni570B"/>
8310408-        <glyphLoc id="18228" name="uni570C"/>
--
8339316-        <glyphLoc id="18226" name="uni570A"/>
8339317:        <glyphLoc id="18227" name="uni570B"/>
8339318-        <glyphLoc id="18228" name="uni570C"/>
--
8368226-        <glyphLoc id="18226" name="uni570A"/>
8368227:        <glyphLoc id="18227" name="uni570B"/>
8368228-        <glyphLoc id="18228" name="uni570C"/>
--
8405322-      <ClassDef glyph="uni570A" class="1"/>
8405323:      <ClassDef glyph="uni570B" class="1"/>
8405324-      <ClassDef glyph="uni570C" class="1"/>
--
8455683-    <mtx name="uni570A" height="256" tsb="15"/>
8455684:    <mtx name="uni570B" height="256" tsb="11"/>
8455685-    <mtx name="uni570C" height="256" tsb="12"/>
```

Now I will test more code points and see what I get out of it.

**Comment by loveencounterflow** [comment]
More data: I tested all codepoints in 

```
[ 0x3000, 0x303f, ], # u-cjk-sym
[ 0x3400, 0x4dbf, ], # u-cjk-xa
[ 0x4e00, 0x9fff, ], # u-cjk
```
and found the following missing ranges:

```
missing: 　 0x3000 .. 〄 0x3004
missing: 々 0x3005 .. 〘 0x3018
missing: 〝 0x301D .. 〟 0x301F
missing: 〡 0x3021 .. 〪 0x302A
missing: 〾 0x303E .. 〿 0x303F
missing: 一 0x4E00 .. 龦 0x9FA6
missing: 龴 0x9FB4 .. 龼 0x9FBC
missing: 鿌 0x9FCC .. 鿿 0x9FFF
```

The missing outlines in 0x3000 and the last few positions before 0xfff are expected as these are ideographic space and undefined, respectively, but the majority of the rest should display.

**Comment by HinTak** [comment]
@duelafn @loveencounterflow : I guess you are lucky that I am not really a freetype-py guy, but a freetype guy. The problem is none of the above - it is rather a "poorly" documented behavior of freetype , in combination to how the new example is written, and special to  Sun-ExtA and some older fonts . FreeType prefers to load the embedded bitmap, if you ask for a size for which the font has embedded bitmap.

- the vera fonts don't have embedded bitmaps, the sun-extA font has embedded bitmap for size 12, 13, 14, 15, 16, 17 .

- You asked for size 12 (`face.set_char_size( 12*64 )`)

- freetype sees that there is a size 12 bitmap in sun-extA, so it does not even try loading the outlines, and just load the bitmap instead.

There are a few ways of working around this, the simplest is just to use a size for which bitmap does not exist (e.g. size 18, `face.set_char_size( 18*64 )` ). The more correct way is to tell freetype not to load bitmap's, with 
```
from freetype import *
...
face.load_char('國', FT_LOAD_DEFAULT | FT_LOAD_NO_BITMAP)
```

or `face.load_char('國', freetype.FT_LOAD_DEFAULT | freetype.FT_LOAD_NO_BITMAP)` in one line.

BTW, my earlier comment about loading by id is, `face.load_glyph(18227, FT_LOAD_DEFAULT | FT_LOAD_NO_BITMAP)` (id 18227 is that character).

Anyway, I found this out by trying the earlier vector examples, `glyph-outline-cairo.py` `glyph-vector-2-cairo.py` with this font. (BTW, I wrote those two, from adapting earlier work...) - and they do work with this glyph + font; then I realize it is the `FT_LOAD_NO_BITMAP` load flag you need for outline decomposition.

To make it fool-proof, I'd suggest @duelafn modify the example to do both - a large size (for which bitmap is unlikely to exist - embedded bitmaps are typically for the readability at the lower-end of sizes), and with `FT_LOAD_NO_BITMAP`.

**Comment by HinTak** [comment]
Aparently I have enough permission to push the two suggestions myself. So I did.

**Comment by duelafn** [comment]
Awesome and excellent! Thanks!
