### ISSUE TITLE
No wheel for Python 3.7 macOS 64-bit

### ISSUE THREAD

**Issue by justvanrossum** [rougier/freetype-py#119]
With Python 3.7.6 for 64 bit on macOS 10.15 (https://www.python.org/ftp/python/3.7.6/python-3.7.6-macosx10.9.pkg), `pip install freetype-py` picks up `freetype_py-2.1.0.post1-py2.py3-none-any.whl`, which doesn't contain the freetype dylib.

**Comment by justvanrossum** [comment]
See also this test repo:
https://github.com/justvanrossum/ftghcimac/commit/ff2ec54aa1d12488dc003b080286672e86f38ab0/checks?check_suite_id=413753112

(I noticed because my github actions CI started failing)

**Comment by madig** [comment]
Does it work if you pin your CI pip to 19.3.1?

**Comment by anthrotype** [comment]
I can repro this on my mac as well, running python 3.7. I think it has something to do with the latest pip 20 released a couple days ago. If I `pip install pip==19.3.1` and try again to `pip install freetype-py` it downloads the correct wheel...

**Comment by justvanrossum** [comment]
Yup, pinning pip to 19.3.1 fixes it. Thanks!

**Comment by anthrotype** [comment]
fixed in pip 20.0.2
pypa/pip#7626
