### ISSUE TITLE
Stroke width and projective transformation

### ISSUE THREAD

**Issue by SunHaozhe** [rougier/freetype-py#130]
Thanks for this awesome project, this is one of the few python solutions which seem to allow me to apply affine transformations to TrueType/OpenType glyphs before rendering (rasterising) them to pixels. 

However, I would like to know if it is possible to change the stroke width of the rendered glyphs?

Stroke width can be specified in `PIL` library by `stroke_width` argument of [PIL.ImageDraw.text() function](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.text). The drawback is that this function operates on pixels instead of the vector representation of glyphs. Is the stroke width specification supported by `freetype-py` somehow?

Furthermore, I would like to know if [perspective/projective transformation](https://web.archive.org/web/20150222120106/xenia.media.mit.edu/~cwren/interpolator/) is supported somehow? Projective transformation is the generalisation of affine transformation with 2 additional parameters, which can be used to simulate different angles of view. 

Thanks for your help!

**Comment by HinTak** [comment]
Stroke width is the first argument of the Stroker class, I think. See the `*outline*` examples. Afaic there is no python example for the FT_Set_Transform` routine for affine transformation - you can read the upstream documentations and contribute one ;)

**Comment by HinTak** [comment]
Here is the relevant part of doc: https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_set_transform

**Comment by SunHaozhe** [comment]
Hi, @HinTak 

It seems to me that the `FT_Set_Transform` routine for affine transformation exists, as shown in the doc

[https://freetype-py.readthedocs.io/en/latest/face.html#freetype.Face.set_transform](https://freetype-py.readthedocs.io/en/latest/face.html#freetype.Face.set_transform)

Did I misunderstand something?

**Comment by HinTak** [comment]
@SunHaozhe same thing - the python code provides an object interface to the underlying c code. The two URLs point to the same underlying functionality. You can use an object-like interface or c-like interface to achieve the same purpose, depending on your preference.
