### ISSUE TITLE
New release with pyinstaller fix

### ISSUE THREAD

**Issue by psb1558** [rougier/freetype-py#163]
Could we have a new release on GitHub and PyPi with the recent pyinstaller fix? It would be hugely helpful to me, and would spare me the daunting prospect of building freetype on several platforms.

Thanks!

**Comment by psb1558** [comment]
Thanks!

**Comment by madig** [comment]
Hi, I can look at this, but am currently busy with other stuff, no promises. I likely need to update the embedded FreeType and HarfBuzz versions...

**Comment by psb1558** [comment]
No hurry, from my point of view, as long as its not forgotten. Glad to have it whenever it can be done.

**Comment by madig** [comment]
https://github.com/rougier/freetype-py/releases/tag/v2.4.0
