### ISSUE TITLE
Freetype.dll provided by other software

### ISSUE THREAD

**Issue by gtojty** [rougier/freetype-py#18]
A quick check of the freetype.dll in some other softwares (I am using WinPython 64 bit and I use freetype-py __init__.py file to specify the path of the dll, note that this is the freetype-py installed via pip install freetype-py, I assume the freetype-py.0.5.3 is similar):

1) GTK+ 3.6.4 (both 32 bit and 64 bit versions): freetype.dll is called: "libfreetype-6.dll" (32 bit) (for 64 bit, libfreetype.dll.a), the freetype-py throws the error: WindowsError: [Error 126] The specified module could not be found (for 64 bit, WindowsError: [Error 193] %1 is not a valid Win32 application), is thrown.

2) Gimp 2 (2.8.14, version under Windows): freetype.dll is called: "freetype6.dll" (32 bit)(for 64 bit, "libfreetype-6.dll"), and the same error is thrown by freetype-py, though Gimp 2 itself can be run without problem.

3) Inkscape-0.48.5 wind32 (version under Windows): freetype.dll is called: "freetyp6.dll", and our code throw the error:  WindowsError: [Error 193] %1 is not a valid Win32 application.

It seems that freetype-py (especially under 64 bit Win7) needs to use its own freetype.dll to run. There is a necessity to provide latest win 7 version of freetype.dll (both 32 bit and 64 bit versions).

Tao

**Comment by Tcll** [comment]
replace freetype/raw.py with my version and everything should work ;)
https://copy.com/9rNzsPqNaBPuyuXH

already made a pull request a few days back.

I'd recommend using the current latest freetype binary though: ;)
x86: https://copy.com/7j3zbjV8VEyVbl0x
x64: https://copy.com/mxZKZGoXR96XEXT4

credit to Matt Sitton for everything.
