### ISSUE TITLE
Full example of rendering SVG text

### ISSUE THREAD

**Issue by ianhoolihan** [rougier/freetype-py#19]
Hi rougier,

I'd find it useful if there was a full example for rendering the entire outline of a word using Matplotlib, as opposed to just one character (as in ./examples/glyph-vector.py). Is this relatively easy for you to do? If not, or you're currently busy, let me know and I can try to figure it out myself.

PS -- my use case is essentially getting a vectorized output of e.g. the wordle example.

**Comment by rougier** [comment]
If you can code it and make a pull request, that would be great (I'm a bit busy at the moment).

**Comment by ianhoolihan** [comment]
For other reasons I've moved to Java. I still think the example will be useful, but I'm afraid I'll be spending the next wee while trying to wrap my head around Java, so I won't be able to help.
