### ISSUE TITLE
pip pulling in wrong version from pypi.

### ISSUE THREAD

**Issue by mdsitton** [rougier/freetype-py#22]
For some reason when trying to install freetype-py with pip it pulls in freetype-py-1.0: https://pypi.python.org/pypi/freetype-py/1.0

instead of the current version freetype-py-0.5.3

Currently i've been working around this by installing from a url like so:
pip install https://pypi.python.org/packages/source/f/freetype-py/freetype-py-0.5.3.tar.gz

it can be a bit of a pain though, any ideas?

**Comment by rougier** [comment]
I  think pypi is respecting the version number. I should bump release number to 1.0.1 to avoid the mess.
Any objections ?

**Comment by mdsitton** [comment]
Sounds good.

**Comment by rougier** [comment]
Done. And I forgot your other PR in the process...
Can you rebase it on master ?
I close this one so we can continue with the other PR.

**Comment by mdsitton** [comment]
yeah i can do that

**Comment by rougier** [comment]
Thanks.

**Comment by mdsitton** [comment]
Both have been rebased.
