### ISSUE TITLE
New player in town

### ISSUE THREAD

**Issue by rougier** [rougier/freetype-py#25]
Some work on different freetype bindings:

https://github.com/ldo/python_freetype

**Comment by ldo** [comment]
Note I try to make my Python bindings take advantage of the high-level nature of Python. See how I implement the Matrix and Vector types, for example.

**Comment by mdsitton** [comment]
Yes, however there could be performance implications with doing that.

**Comment by ldo** [comment]
“Premature Optimization Is The Root Of All Evil.”

Or, in other words, if you were worried about efficiency,you wouldn’t be using Python.

**Comment by mdsitton** [comment]
A valid point.

**Comment by mdsitton** [comment]
Main reason i mentioned it, was had a matrix class that was something similar to what you have.(not freetype related though) Eventually i moved it over to cython.

**Comment by ldo** [comment]
I admit there is a certain amount of duplication going on. For example, I also have Matrix and Vector types in [Qahirah](https://github.com/ldo/qahirah). If there were a standard Python module for 2D matrices and vectors, we could rely on that.
