### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by QuLogic** [rougier/freetype-py#28]
The latest master includes an important fix for Python 3.4 (#21), and is causing trouble when unbundling from vispy. A new release would make this much easier.

**Comment by rougier** [comment]
Thanks. One issue has just been opened. I'll try to fix it and make a new release.

**Comment by QuLogic** [comment]
Ping?

**Comment by rougier** [comment]
Oh, thanks. I'll try to do it today or tomorrow. Do not hesitate to ping me again.

**Comment by rougier** [comment]
Done.
