### ISSUE TITLE
how do I get the glyph's decender??

### ISSUE THREAD

**Issue by Tcll** [rougier/freetype-py#31]
basically, here's my issue:
http://lh3.ggpht.com/-GmqDWP3qLbI/VXy9r5LRGKI/AAAAAAAAJPc/qeai--pHARg/s802/Screenshot%252520-%25252006132015%252520-%25252007%25253A22%25253A11%252520PM.png

with PIL and PyGame I can get the glyph height and max height...
but with this, I can't seem to get the proper max height and a very wonky glyph height :/

I need the bitmap w/h for the GL texture, and the max w/h for the transformations.

EDIT:
the base line for drawing the glyphs is positioned at the upper left, while the characters are drawn to the bottom right.

**Comment by Tcll** [comment]
btw, separate issue...
that box character where the refresh button is is this character: ↻

**Comment by rougier** [comment]
Have a look at https://github.com/rougier/freetype-py/blob/master/examples/opengl.py

It seem you're using glyph height and width that relates to the bitmap width and height. If you want to have the glyph logical height and width, you have to take bitmap_top and bitmap_left into account.

**Comment by Tcll** [comment]
yea, that example does not do what mine does, and modifying mine would require me to rewrite my whole interface (things for centering text on buttons or other rectangular areas)

> If you want to have the glyph logical height and width, you have to take bitmap_top and bitmap_left into account.

I have, for a character like `"`, the bitmap `rows` is 5 while the `bitmap_top` (aka ascension) is 11, and for a character like `p`, `rows` is 14 while `bitmap_top` is 10 for size 18 font.
I'm currently taking the point into account and the base line is only valid for characters in the ASCII range(128) which maxes out at 14 with an overflow of 4, so here's something I'm trying:

    bitmap    = F.glyph.bitmap
    data_w    = bitmap.width
    height    = bitmap.rows
    ascender  = F.glyph.bitmap_top
    overflow  = 0 if ascender>height else height-ascender
    data_h    = pt+overflow

data_w and data_h is all I need...
I can map the bitmap pixels to a dynamic bitmap

trust me, I've already pulled my hair out before asking for help ;)

**Comment by Tcll** [comment]
ok, it's not quite perfect, but the vertical positioning works right now:
http://lh3.ggpht.com/-eU35dmxKReQ/VX0HQEs-biI/AAAAAAAAJP0/PAI3ruKhldg/s802/Screenshot%252520-%25252006142015%252520-%25252012%25253A45%25253A33%252520AM.png

here's what I've got so far:

    bitmap    = F.glyph.bitmap
    width     = bitmap.width
    height    = bitmap.rows
    ascender  = F.glyph.bitmap_top
    overflow  = 0 if ascender>height else height-ascender

    data_w    = max([width, F.glyph.bitmap_left])
    data_h    = pt+overflow

    data = [0]*(data_w*data_h)

    for y in range(height):
        for x in range(width):
            data[((y+(pt-ascender))*data_w)+x] = bitmap.buffer[(y*width)+x]

    data = sum([[p,p] for p in data],[])

what else could I use to solve this??

**Comment by rougier** [comment]
What is the problem now ?

Useful resource: http://www.freetype.org/freetype2/docs/glyphs/glyphs-3.html

**Comment by Tcll** [comment]
> What is the problem now ?

me not knowing hardly anything about the raw handling... lol
(I was rather expecting most of this sutomated like PyGame or PIL/Pillow)

> Useful resource:

indeed that helps alot with the classifications, though it's confusing when it comes to actually positioning the stuff...

how do I get the bearingX so I can space my text appropriately??

just to state, I'm not currently worrying about the line-spacing as my interface only supports a quad w/h position

**Comment by rougier** [comment]
`glyph.advance.x`

**Comment by Tcll** [comment]
jsyk, I'm working on it...
this doesn't give me any index errors:
http://lh3.ggpht.com/-_3BpUEBTA_Q/VX0X5QpRGGI/AAAAAAAAJQM/lxaYnPf8wBc/s802/Screenshot%252520-%25252006142015%252520-%25252001%25253A54%25253A43%252520AM.png

glyph.advance.x commonly returns `1152`/64 = 18 `+bitmap.width` (no more index error)

so that's where I'm at now...

**Comment by rougier** [comment]
Do not add bitmap.width

**Comment by Tcll** [comment]
if I don't, I get an index error because the bitmap width is larger than the dynamic width...

should I do a max() test??
(I'm tired right now and having trouble thinking) lol

**Comment by rougier** [comment]
You have an error in your code then. I woudl advise to study https://github.com/rougier/freetype-py/blob/master/examples/texture_font.py.

**Comment by Tcll** [comment]
ok, now that I'm waking up, I think I'm seeing it:

    |  |           |       |
    1  2           3       4

1: Origin
2: bearingX or OffsetX
3: Bitmap width
4: Glyph Advance (from 2)

most characters appear like this:
C 1 9 11
but other characters:
ε -1 6 4

so I guess build an image based on the `max( bitmap.width, F.glyph.advance.x/64 )`
and I'm guessing add the offset if >0 (since my interface can't do -1)

I'll post back my results

btw, texture_font didn't really help... the resource from earlier helped me understand the advance, but I didn't understand it was advance OR width (whichever was greater)
and the offset being below 0 threw me off as well.

**Comment by Tcll** [comment]
got it!
http://lh3.ggpht.com/-SmxoWaZNJS4/VX2eVqs00XI/AAAAAAAAJQk/4d_blAkNEzw/s802/Screenshot%252520-%25252006142015%252520-%25252011%25253A26%25253A47%252520AM.png

it lookes just as good as PyGame now :)
screw Pillow's disgusting implementation :P
lol

here's the code:

    bitmap    = F.glyph.bitmap
    width     = bitmap.width
    height    = bitmap.rows
    ascender  = F.glyph.bitmap_top
    overflow  = 0 if ascender>height else height-ascender

    offset    = F.glyph.bitmap_left if F.glyph.bitmap_left>0 else 0

    data_w    = max([width, F.glyph.advance.x/64])+offset
    data_h    = pt+overflow

    #print data_w

    data = [0]*(data_w*data_h)

    for y in range(height):
        for x in range(width):
            data[((y+(pt-ascender))*data_w)+(x+offset)] = bitmap.buffer[(y*width)+x]

    data = sum([[p,p] for p in data],[]) # convert to LA

note that `data` is the final image.
it's drawn in LA format so I can later apply color through glColor3f()
(Alpha format only draws black)
