### ISSUE TITLE
Freetype fails to detect kerning data

### ISSUE THREAD

**Issue by kelvin13** [rougier/freetype-py#36]
On many fonts that certainly have kerning pairs, `Face.has_kerning` is reporting False and the kern pairs come out to be zero.

```
import freetype

F = freetype.Face('FiraSans-Book.otf')
print(F.has_kerning)

>> False
```

**Comment by rougier** [comment]
Do you know if Fira has actual kerning information ?

**Comment by kelvin13** [comment]
Yes, it does

**Comment by rougier** [comment]
Ok, I will try to investigate using same method as the bbox

**Comment by rougier** [comment]
From the script below, I get some flags but none for the kerning. Maybe kerning is present but freetype does not advertise it.

```
import freetype
face = freetype.Face('FiraSans-Book.ttf')

print("Scalable:         ", bool(face.face_flags & freetype.FT_FACE_FLAG_SCALABLE))
print("Fixed sizes:      ", bool(face.face_flags & freetype.FT_FACE_FLAG_FIXED_SIZES))
print("Fixed width:      ", bool(face.face_flags & freetype.FT_FACE_FLAG_FIXED_WIDTH))
print("SFNT:             ", bool(face.face_flags & freetype.FT_FACE_FLAG_SFNT))
print("Horizontal:       ", bool(face.face_flags & freetype.FT_FACE_FLAG_HORIZONTAL))
print("Vertical:         ", bool(face.face_flags & freetype.FT_FACE_FLAG_VERTICAL))
print("Kerning:          ", bool(face.face_flags & freetype.FT_FACE_FLAG_KERNING))
print("Fast glyphs:      ", bool(face.face_flags & freetype.FT_FACE_FLAG_FAST_GLYPHS))
print("Multiple masters: ", bool(face.face_flags & freetype.FT_FACE_FLAG_MULTIPLE_MASTERS))
print("Glyph names:      ", bool(face.face_flags & freetype.FT_FACE_FLAG_GLYPH_NAMES))
print("External stream:  ", bool(face.face_flags & freetype.FT_FACE_FLAG_EXTERNAL_STREAM))
print("Hinter:           ", bool(face.face_flags & freetype.FT_FACE_FLAG_HINTER))
print("CID Keyed:        ", bool(face.face_flags & freetype.FT_FACE_FLAG_CID_KEYED))
print("Tricky:           ", bool(face.face_flags & freetype.FT_FACE_FLAG_TRICKY))
```

**Comment by rougier** [comment]
Also, from [freetype documentation](http://www.freetype.org/freetype2/docs/tutorial/step2.html):

Not all font formats contain kerning information, and not all kerning formats are supported by FreeType; in particular, for TrueType fonts, the API can only access kerning via the ‘kern’ table. **OpenType kerning via the ‘GPOS’ table is not supported!** You need a higher-level library like HarfBuzz, Pango, or ICU, since GPOS kerning requires contextual string handling.

**Comment by kelvin13** [comment]
Fira, like the vast majority of modern fonts only has GPOS kerning and no ttf “kern” table. So that would explain it. But how can freetype lack such a thing? It sounds pretty essential

**Comment by rougier** [comment]
It is essential and can become pretty complex for some languages . I imagine this is the reason why freetype doesn't handle it outside the kern table. You'll have to use HarfBuzz or pango.

**Comment by kelvin13** [comment]
is it possible for freetype to just return the opentype kerning table itself so I can read latin kern pairs off of it?

**Comment by rougier** [comment]
I don't know. You should ask on the freetype mailing list.

**Comment by kelvin13** [comment]
ugh so the [FAQ](http://www.freetype.org/freetype2/docs/ft2faq.html#general-what) says `Well, the engine already reads OpenType/CFF files perfectly. What it doesn't do is handling ‘OpenType Layout’ tables.`
