### ISSUE TITLE
Hello World example dtype problem

### ISSUE THREAD

**Issue by niloxx** [rougier/freetype-py#37]
Hey guys, I was just passing by trying the code of examples/hello-world.py and I got this error:

> Traceback (most recent call last):
>   File "testing.py", line 39, in <module>
>     Z[y:y+h,x:x+w] += numpy.array(bitmap.buffer).reshape(h,w)
> TypeError: Cannot cast ufunc add output from **dtype('float64')** to **dtype('int32')** with casting rule 'same_kind' 

So I changed the line where you create Z to make it float64 and now it works like a charm:

` Z = numpy.zeros((height,width), dtype=numpy.float64)`

Maybe it is a problem of my settings, I am using Windows 7 32 bits and Python 2.7 Anaconda.

Best,

Gabriel.

**Comment by rougier** [comment]
Thanks. I think this is related to newer versions of dtype that are less permissive.
Could me make a PR with your fix ?

**Comment by niloxx** [comment]
Yes of course. Sorry for the late answer.

**Comment by rougier** [comment]
Thank you.

**Comment by astrofrog** [comment]
I'm seeing this issue too with recent versions of Numpy
