### ISSUE TITLE
Suggestion: Add more pythonic way to get all character codes

### ISSUE THREAD

**Issue by jiong3** [rougier/freetype-py#41]
Hi,

thanks for the library, very useful! I use it to get a list of all the supported codepoints in a font and it was not immediatly clear to me how to do it. I think a generator might be more pythonic:

```
def get_chars(self):
    charcode, agindex = self.get_first_char()
    yield (charcode, agindex)

    while agindex != 0:
        charcode, agindex = self.get_next_char(charcode, 0)
        yield (charcode, agindex)
```

**Comment by rougier** [comment]
Thanks. Could you make PR so we can test it ?
