### ISSUE TITLE
RuntimeError: Freetype library not found

### ISSUE THREAD

**Issue by StephewZ** [rougier/freetype-py#46]
![h le5bock de 0k zm 83r](https://cloud.githubusercontent.com/assets/24892079/24078946/bd4e3f7c-0cb6-11e7-96d8-6a875f50d6ba.png)

run at python3.4    pip list 
appdirs (1.4.3)
Django (1.10.6)
django-reversion (2.0.8)
freetype-py (1.0.2)
olefile (0.44)
packaging (16.8)
Pillow (4.0.0)
pip (9.0.1)
PyMySQL (0.7.10)
pyparsing (2.2.0)
setuptools (34.3.2)
six (1.10.0)
wheel (0.29.0)
xlwt (1.2.0)

python manage.py runserver

RuntimeError: Freetype library not found

**Comment by rougier** [comment]
This means the freetype library (not the freetype-py) cannot be found. Do you know where it is located by any chance ? Usually it is in `/usr/local`

**Comment by HinTak** [comment]
The screenshot looks like windows. `/usr/local` isn't relevant..

**Comment by StephewZ** [comment]
yeah  it is  windouws10. but it's alright when I use python2.7

**Comment by StephewZ** [comment]
![t3ab9 sob96zvv qjp hz1l](https://cloud.githubusercontent.com/assets/24892079/24086895/5490a384-0d52-11e7-9cd8-523b347d4743.png)
![u2 cubpvu2i4h3m06me q b](https://cloud.githubusercontent.com/assets/24892079/24086897/56d5b1c0-0d52-11e7-950f-d581e2e133d0.png)
It is freetype library？ it dosen't work

**Comment by StephewZ** [comment]
![uxyt7q h jae2jtc 56fi2w](https://cloud.githubusercontent.com/assets/24892079/24088805/fdd1b304-0d69-11e7-9233-ef7c00ed3c5d.png)
![0xl r6d_ p5qpu 7 2xgpv](https://cloud.githubusercontent.com/assets/24892079/24088806/fe80808c-0d69-11e7-8897-bf2facf7c987.png)
I add   dll=ctypes.cdll.LoadLibrary('C:\Windows\System32')   at raw.py
![wqix pi trw p29 82jojl1](https://cloud.githubusercontent.com/assets/24892079/24088812/21041c4a-0d6a-11e7-9181-dbe7401f2e06.png)

**Comment by StephewZ** [comment]
oh  I solved this problem!   I get a freetype.dll for win10 instanceof old one. so simply,but It took me two days.thanks god!
[http://www.dllzj.com/gdx-freetype64.dll/](url)

**Comment by HinTak** [comment]
Do you really want to download the windows freetype dll from random places on the Internet? I am surprised that freetype-py does not provides it, but SharpFont (C# binding for freetype) certainly does. My fork of Font Validator also does - more up to date, and with mac os x freetype dylib also; though because it is cross-compiled with mine rather than with MS VC like SharpFont's, is a bundle of about 5 dll's with the usual oss dependencies rather than a single dll as in the SharpFont provide.

**Comment by HinTak** [comment]
or have an official recommended source of windows freetype dll.

**Comment by rougier** [comment]
Unfortunately I've no experience with Windows and DLL. What would be the best recommended way ?

**Comment by StephewZ** [comment]
Freetype.dll has too many versions，I can't use it download from the official website. So I try this, and It works well.

**Comment by StephewZ** [comment]
http://download.savannah.gnu.org/releases/freetype/        Old freetype download link.The system prompt:Does not support your device(Probably mean it). I've tried many versions.

**Comment by HinTak** [comment]
Afaik, savannah ships only freetype source code - do you actually have a url for dll download from savannah?

And do you actually care about which versions of freetype to use? Most people do not - the external interfaces rarely changes and haven't for decades. If freetype-py actually uses version-specific APIs, it is up to freetype-py to care, not the end user. Freetype provides API's for querying its version - so it is quite easy to adapt to different freetype dll versions even if you use version-specific APIs. For example, I contribute an enhancement to freetype to make font validator's tests possible. It went in at 2.6.1 - so my application code actually checks the found freetype dll as higher than 2.6.1 at those points, or tell the user that he needs to get a more recent freetype.

As I mentioned earlier, the SharpFont project actively maintains and ships freetype windows dlls:

https://github.com/Robmaister/SharpFont.Dependencies

Perhaps it is best to test and adapt freetype-py to those, or co-ordinate with them.

**Comment by StephewZ** [comment]
Yeah, I download from savannah, and my PC says: not support. I do not know why. But when I download 
freetype dll from other web,it works well. Maybe my PC has a problem.

**Comment by StephewZ** [comment]
Thank you for your advice
