### ISSUE TITLE
Not showing actual error with "Freetype library not found"

### ISSUE THREAD

**Issue by HinTak** [rougier/freetype-py#48]
It is very unfortunate in `freetype-py/freetype/raw.py` that any kind of library load errors results in the very unhelpful:

```
RuntimeError: Freetype library not found
```

I notice this because my freetype build was slightly out of sync (stale object files after a fetch/rebase). I only found out my freetype build was slightly out of sync and got the actual error when I ran ctype directly (the FT_UINT_TO_POINTER macro was introduced upstream 10 days ago) like this:

```
$ LD_LIBRARY_PATH=my-dev/freetype2/objs/.libs/ python
>>> from ctypes import *
>>> cdll.LoadLibrary("libfreetype.so.6")  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 435, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 357, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: my-dev/freetype2/objs/.libs/libfreetype.so.6: undefined symbol: FT_UINT_TO_POINTER
>>> 
```

It would be better if `freetype-py/freetype/raw.py` does not lump every load error under `library not found`.

**Comment by HinTak** [comment]
I think perhaps the try/except construct should be removed, or the exception re-throw, after the `library not found` message from freetype-py, since the error message from ctypes is more informative and should not be suppressed or overriden by freetype-py .

**Comment by rougier** [comment]
Yes. The try/except was introduced for Windows mostly (lot of problem when looking for the DLL).
Also, it would be good to check for what version of freetype we're dealing once loaded.

**Comment by HinTak** [comment]
That sounds strange... on linux the error message is more informative without the try/except. One possibility I can see is that in some configuration of windows - with or without some bits of visual studio installed - looking for an non-existent dll is not caught by ctypes on windows, and may cause a GUI pop up and or even launch the visual studio debugger. I can definitely see those being quite undesirable.

python 3.5's ctype documentation has this little paragraph:

```
...The error code is used to automatically raise an OSError exception when the function call fails.

   Changed in version 3.3: Windows errors used to raise WindowsError, which is now an alias of OSError.
```

python 2.7's ctypes documentation has this instead.

```
 The error code is used to automatically raise a WindowsError exception when the function call fails.

```

I wonder if doing a `if OS==windows ...` and do something different.

**Comment by rougier** [comment]
I think the current loaded is comes from this thread https://github.com/rougier/freetype-py/issues/27

**Comment by HinTak** [comment]
I think something like this should be done at least, instead of just `except: raise`. 

```
except Exception as e:
            print str(e)
           raise ...
```

I use wine quite regularly, and quite familiar with it. I worked on wine's IE emulation for a bit and had a few large patches merged.

I think problems in https://github.com/rougier/freetype-py/issues/27 are just people grabbing random freetype dll's from the internet.

**Comment by Utkarsh22Ahuja** [comment]
Hi everyone, please fix this error. I am not able to work with this. RuntimeError: Freetype library not found.

Also the step by step instruction for installation given by you on https://glumpy.readthedocs.io/en/latest/ is not helping. Another doubt, I don't understand what is python3 folder? Where am I supposed to copy those dlls? And the statement either of the dlls, I am implying for win64 since my system is on win64. What exactly are you guys targetting?

**Comment by madig** [comment]
Wrong issue tracker? This project has nothing to do with Glumpy.

**Comment by HinTak** [comment]
Grumpy depends on opengl, which I suppose then depends on freetype etc. But anyway, the correct place to report glympy-related thing is https://github.com/glumpy/glumpy/issues

**Comment by Utkarsh22Ahuja** [comment]
Sorry Guys for the right query at wrong place.

**Comment by rougier** [comment]
glumpy no grumpy :)
