### ISSUE TITLE
Does it support unicode?

### ISSUE THREAD

**Issue by yzldw333** [rougier/freetype-py#54]
I use it to make pictures of Chinese words, but it since that doesn't support.

**Comment by jiong3** [comment]
Rendering Chinese characters shouldn't be a problem, what exactly doesn't work?

**Comment by HinTak** [comment]
You need the latest code  ( https://github.com/rougier/freetype-py/pull/52 ) if you are using python 2.x, instead of 3.x . One of the most recent changes a few days ago fixes encoding issue for python 2.x .

**Comment by HinTak** [comment]
![example_1-cairo](https://cloud.githubusercontent.com/assets/14662953/25557866/ad69101a-2d12-11e7-8724-170cacac4859.png)

Here is example 1 quickly adapted to do Chinese. As I expected, just using a chinese-capable font and a chinese phrase would do, so the change is only two lines:
```
@@ -45,8 +45,8 @@ def main():
     matrix  = FT_Matrix()
     face    = FT_Face()
     pen     = FT_Vector()
-    filename= 'Vera.ttf'
-    text    = 'Hello World !'
+    filename= 'DroidSansFallbackFull.ttf'
+    text    = '你好嗎!'
     num_chars = len(text)
```

OTOH, as I mentioned above, python 2.x does strings and unicodes somewhat differently; so this change for example 1 only works on python 3.x. My fix ( https://github.com/rougier/freetype-py/pull/52 ) only fixes unicode processing for the emoji example. TODO.

**Comment by HinTak** [comment]
I tested both of these answers for python2, and both work. You can either put this line near the top:

```
from __future__ import unicode_literals
```

which enables python 2.x to process strings python 3.x style, or add a `decode('utf8')` manually like this:

```
@@ -45,8 +46,9 @@ def main():
     matrix  = FT_Matrix()
     face    = FT_Face()
     pen     = FT_Vector()
-    filename= 'Vera.ttf'
-    text    = 'Hello World !'
+    filename= 'DroidSansFallbackFull.ttf'
+    text    = '你好嗎!'
+    text = text.decode('utf8')
     num_chars = len(text)
```

Both of these work, you only need one of them. The first one is probably easiest.
