### ISSUE TITLE
Updated package on pypi

### ISSUE THREAD

**Issue by rdavidso** [rougier/freetype-py#61]
The 1.0.2 version on pypi/pip is very out of date, and does not reflect the latest documentation!  Please provide a new release.

**Comment by rougier** [comment]
Yes, I'll do so today. Please remind me if it's not the case.

**Comment by scw** [comment]
Thanks for your work on this project, it's a useful one! I agree that it'd be great to have a new formal release when you have time.

**Comment by rougier** [comment]
I'm so late... Will do that now, come back here when done.

**Comment by rougier** [comment]
Done: https://pypi.python.org/pypi/freetype-py/1.1
