### ISSUE TITLE
trim symbol list down to match visual studio window build of freetype

### ISSUE THREAD

**Issue by HinTak** [rougier/freetype-py#65]
See
https://github.com/rougier/freetype-py/issues/17#issuecomment-345205940

It looks like the typical visual studio build of freetype does not include support for some of the more unix-centric font formats. Consider trimming the symbol list down, although this is arguable since the typical freetype-py users are unix-based.

**Comment by rougier** [comment]
Is there a liste of such symbols somewhere ?

**Comment by HinTak** [comment]
Freetype ships a visual studio project file (contributed from somebody else. )It should be possible to do a visual studio build from it and read the symbol list. I can do it at some point.

**Comment by rougier** [comment]
Thanks for the offer. Is it worth the effort?

**Comment by HinTak** [comment]
It is not much an effort. I ships mingw cross-compiled Freetype because it is easier for me and it matches the Unix feature set better, but the visual studio route needs to be looked at, at some point, since that's more natural to windows developers. So I'll do it at some point and perhaps push some suggestions upstream also if I finish anything significantlo missing in vs-built Freetype.

**Comment by rougier** [comment]
Ok, thanks.

**Comment by HinTak** [comment]
It is actually not too bad - my mingw-cross compiled freetype have only 5 more symbols, these BDF ones and

```
FT_Get_CID_From_Glyph_Index
FT_Get_CID_Is_Internally_CID_Keyed
FT_Get_CID_Registry_Ordering_Supplement
``` 

I'll go about asking the freetype people adding those 5 to keep them in syn, but for how just protecting the *BDF* nes should do since the CID ones are not in freetype-py yet.
