### ISSUE TITLE
Segfault when Face.get_name_index() out of bounds

### ISSUE THREAD

**Issue by madig** [rougier/freetype-py#68]
```Python
from freetype import *

f = Face("Vera.ttf")  # From the examples dir
f.get_name_index(8805)
```

**Comment by rougier** [comment]
Thanks for the report. I guess I forget to test if the given index was legit. Could you make a PR ?

**Comment by madig** [comment]
Or rather, `FT_Get_Name_Index` expects a `FT_String*` and I just passed in garbage. Throwing an 'invalid argument' exception when not passing in a b'string' may be enough.
