### ISSUE TITLE
how to change text color by cairo

### ISSUE THREAD

**Issue by ronyuzhang** [rougier/freetype-py#70]
ctx.set_source_rgb() It doesn't work.

**Comment by rougier** [comment]
Do you have a precise example in mind?

**Comment by ronyuzhang** [comment]
code in hellow-world-cairo.py  
    for c in text:
        face.load_char(c)
        bitmap = slot.bitmap
        top = slot.bitmap_top
        left = slot.bitmap_left
        w,h = bitmap.width, bitmap.rows
        y = height-baseline-top
        kerning = face.get_kerning(previous, c)
        x += (kerning.x >> 6)
        # cairo does not like zero-width bitmap from the space character!
        if (bitmap.width > 0):
            glyph_surface = make_image_surface(face.glyph.bitmap)
            ctx.set_source_surface(glyph_surface, x, y)
            # ctx.set_source_rgb(0,0,1)
            ctx.paint()
        x += (slot.advance.x >> 6)

**Comment by HinTak** [comment]
set_source_rgb() replaces set_source_surface() , not in conjunction with it. You need to set mask with the glyph then plaint with color source.
