### ISSUE TITLE
Request to release new tarball 1.2 release

### ISSUE THREAD

**Issue by pnemade** [rougier/freetype-py#71]
Hi,
I saw few commits since last I submitted patch to setup.py that advanced version to 1.2 but tarball 1.2 yet not released. From the last 1.1 tarball we still have issue of egg-info generated with 1.0.2 version.

I request to release new tarball that will then have matching tarball version and egg-info version.

**Comment by rougier** [comment]
Sounds a good idea. What is the problem exactly with the egg version ?

**Comment by pnemade** [comment]
Same issue. The current release generate egg-info as
/usr/lib/python2.7/site-packages/freetype_py-1.0.2-py2.7.egg-info/
See the generated version as 1.0.2 and not 1.1
