### ISSUE TITLE
README.md instead of README.md

### ISSUE THREAD

**Issue by rougier** [rougier/freetype-py#75]
It seems [Pypi](https://pypi.org/project/freetype-py/) does not interpret restructured text but interpret markdown. Hence, it would be better to use a `README.md`. 

The list of contributors should be updated also.

**Comment by anthrotype** [comment]
It’s the other way around, PyPI only supports plain text or restructuredtext, not markdown. If it doesn’t display correctly the rst may be malformed.

**Comment by anthrotype** [comment]
you can pip install `docutils` and `pygments` and then do `python setup.py check --restructuredtext --strict` to verify that the rst is syntactically correct. If it passes, then it will be rendered properly on PyPI. 
You can also use `restview` package to preview the rendered html locally in your browser.

**Comment by anthrotype** [comment]
relevant https://github.com/pypa/python-packaging-user-guide/issues/210#issuecomment-368198286

**Comment by rougier** [comment]
Oh thanks, didn't know.
